sudo: required
install: true
language: scala

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.gradle
    - $HOME/.docker

scala:
   - 2.11.8

services:
  - docker

before_script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - sbt assembly # also runs tests
  - docker build -t bencinmonitor/d2:latest .

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push bencinmonitor/d2:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "production" ]; then
    docker push bencinmonitor/d2:production;
    fi